# Generated by Django 5.2.17 on 2026-09-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='require_sequential',
            field=models.BooleanField(default=False, help_text='Also require the previous lesson to be completed before unlocking'),
        ),
    ]
