# Generated by Django 5.2.17 on 2026-09-16 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_academies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academymembership',
            name='academy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='academies.academy'),
        ),
        migrations.AddField(
            model_name='academymembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='academymembership',
            constraint=models.UniqueConstraint(fields=('academy', 'user'), name='uniq_academy_member'),
        ),
    ]
