# Generated by Django 5.2.17 on 2026-09-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academy',
            name='is_active',
        ),
        migrations.AddField(
            model_name='academy',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academy',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academy',
            name='status',
            field=models.CharField(choices=[('onboarding', 'Onboarding'), ('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='onboarding', max_length=12),
        ),
        migrations.AddField(
            model_name='academy',
            name='suspended_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academy',
            name='tagline',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='academy',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='academy',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
