# Generated by Django 5.2.17 on 2026-09-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0003_remove_academy_is_active_academy_activated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
